/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectolavadero.Interfaces;

/**
 *
 * @author juaco
 */
public class registroEmpleadoInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form registroEmpleadoInterfaz
     */
    public registroEmpleadoInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        PanelIzq = new javax.swing.JPanel();
        InicioBT = new javax.swing.JButton();
        CotizacionBT = new javax.swing.JButton();
        VehiculosBT = new javax.swing.JButton();
        ClientesBT = new javax.swing.JButton();
        EquipoBT = new javax.swing.JButton();
        InventarioBT = new javax.swing.JButton();
        ReportesBT = new javax.swing.JButton();
        CatalogoBT = new javax.swing.JButton();
        LogoBT = new javax.swing.JButton();
        PanelSuperior = new javax.swing.JPanel();
        Busqueda = new com.mycompany.proyectolavadero.Interfaces.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        Soporte = new javax.swing.JButton();
        Usuario = new javax.swing.JButton();
        PanelCentral = new javax.swing.JPanel();
        TextoCabeza = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        CI = new javax.swing.JLabel();
        Telf = new javax.swing.JLabel();
        Direccion = new javax.swing.JLabel();
        Correo = new javax.swing.JLabel();
        EquipoLavado = new javax.swing.JLabel();
        CITxt = new javax.swing.JTextField();
        TelfTxt = new javax.swing.JTextField();
        DireccionTxt = new javax.swing.JTextField();
        CorreoTxt = new javax.swing.JTextField();
        EquipoLavadoTxt = new javax.swing.JTextField();
        NombreTxt = new javax.swing.JTextField();
        ApellidoTxt = new javax.swing.JTextField();
        Foto = new javax.swing.JPanel();
        FotoBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelIzq.setBackground(new java.awt.Color(17, 17, 29));

        InicioBT.setBackground(new java.awt.Color(17, 17, 29));
        InicioBT.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        InicioBT.setForeground(new java.awt.Color(255, 255, 255));
        InicioBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/company/proyectolavadero/Iconos/IconosIngresoEmpleado/casa (4).png"))); // NOI18N
        InicioBT.setText("Inicio");
        InicioBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioBTActionPerformed(evt);
            }
        });

        CotizacionBT.setBackground(new java.awt.Color(17, 17, 29));
        CotizacionBT.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        CotizacionBT.setForeground(new java.awt.Color(255, 255, 255));
        CotizacionBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/company/proyectolavadero/Iconos/IconosIngresoEmpleado/carro-de-la-carretilla.png"))); // NOI18N
        CotizacionBT.setText("Cotizacion");
        CotizacionBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CotizacionBTActionPerformed(evt);
            }
        });

        VehiculosBT.setBackground(new java.awt.Color(17, 17, 29));
        VehiculosBT.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        VehiculosBT.setForeground(new java.awt.Color(255, 255, 255));
        VehiculosBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/company/proyectolavadero/Iconos/IconosIngresoEmpleado/coche frontal.png"))); // NOI18N
        VehiculosBT.setText("Vehiculos");

        ClientesBT.setBackground(new java.awt.Color(17, 17, 29));
        ClientesBT.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        ClientesBT.setForeground(new java.awt.Color(255, 255, 255));
        ClientesBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/company/proyectolavadero/Iconos/IconosIngresoEmpleado/clientes.png"))); // NOI18N
        ClientesBT.setText("Clientes");

        EquipoBT.setBackground(new java.awt.Color(17, 17, 29));
        EquipoBT.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        EquipoBT.setForeground(new java.awt.Color(255, 255, 255));
        EquipoBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/company/proyectolavadero/Iconos/IconosIngresoEmpleado/trabajo-en-equipo.png"))); // NOI18N
        EquipoBT.setText("Equipo de Lavado");

        InventarioBT.setBackground(new java.awt.Color(17, 17, 29));
        InventarioBT.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        InventarioBT.setForeground(new java.awt.Color(255, 255, 255));
        InventarioBT.setText("Inventario");

        ReportesBT.setBackground(new java.awt.Color(17, 17, 29));
        ReportesBT.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        ReportesBT.setForeground(new java.awt.Color(255, 255, 255));
        ReportesBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/company/proyectolavadero/Iconos/IconosIngresoEmpleado/informe-seo.png"))); // NOI18N
        ReportesBT.setText("Reportes");

        CatalogoBT.setBackground(new java.awt.Color(17, 17, 29));
        CatalogoBT.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        CatalogoBT.setForeground(new java.awt.Color(255, 255, 255));
        CatalogoBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/company/proyectolavadero/Iconos/IconosIngresoEmpleado/catalogar.png"))); // NOI18N
        CatalogoBT.setText("Catalogo");

        LogoBT.setBackground(new java.awt.Color(17, 17, 29));
        LogoBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/company/proyectolavadero/Iconos/IconosIngresoEmpleado/Logo.png"))); // NOI18N
        LogoBT.setBorder(null);
        LogoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelIzqLayout = new javax.swing.GroupLayout(PanelIzq);
        PanelIzq.setLayout(PanelIzqLayout);
        PanelIzqLayout.setHorizontalGroup(
            PanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIzqLayout.createSequentialGroup()
                .addGroup(PanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIzqLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(PanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VehiculosBT, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClientesBT, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EquipoBT)
                            .addGroup(PanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CatalogoBT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ReportesBT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(InventarioBT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CotizacionBT)
                            .addComponent(InicioBT, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelIzqLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LogoBT)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        PanelIzqLayout.setVerticalGroup(
            PanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIzqLayout.createSequentialGroup()
                .addComponent(LogoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InicioBT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CotizacionBT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(VehiculosBT)
                .addGap(18, 18, 18)
                .addComponent(ClientesBT)
                .addGap(18, 18, 18)
                .addComponent(EquipoBT)
                .addGap(18, 18, 18)
                .addComponent(InventarioBT)
                .addGap(18, 18, 18)
                .addComponent(ReportesBT)
                .addGap(18, 18, 18)
                .addComponent(CatalogoBT)
                .addContainerGap(308, Short.MAX_VALUE))
        );

        Background.add(PanelIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 316, 1024));

        PanelSuperior.setBackground(new java.awt.Color(236, 240, 241));

        Busqueda.setBackground(new java.awt.Color(255, 255, 255));
        Busqueda.setRoundBottomLeft(50);
        Busqueda.setRoundBottomRight(50);
        Busqueda.setRoundTopLeft(50);
        Busqueda.setRoundTopRight(50);

        jLabel1.setText("Buscar");

        javax.swing.GroupLayout BusquedaLayout = new javax.swing.GroupLayout(Busqueda);
        Busqueda.setLayout(BusquedaLayout);
        BusquedaLayout.setHorizontalGroup(
            BusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BusquedaLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        BusquedaLayout.setVerticalGroup(
            BusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        Soporte.setBackground(new java.awt.Color(236, 240, 241));
        Soporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/company/proyectolavadero/Iconos/IconosIngresoEmpleado/soporte-en-linea (1).png"))); // NOI18N
        Soporte.setText("Soporte");
        Soporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoporteActionPerformed(evt);
            }
        });

        Usuario.setBackground(new java.awt.Color(236, 240, 241));
        Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/company/proyectolavadero/Iconos/IconosIngresoEmpleado/avatar.png"))); // NOI18N
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSuperiorLayout = new javax.swing.GroupLayout(PanelSuperior);
        PanelSuperior.setLayout(PanelSuperiorLayout);
        PanelSuperiorLayout.setHorizontalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSuperiorLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 517, Short.MAX_VALUE)
                .addComponent(Soporte)
                .addGap(18, 18, 18)
                .addComponent(Usuario)
                .addGap(25, 25, 25))
        );
        PanelSuperiorLayout.setVerticalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSuperiorLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Soporte)
                    .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        Background.add(PanelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 0, 1124, 90));

        TextoCabeza.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TextoCabeza.setText("   Nuevo Trabajador");
        TextoCabeza.setToolTipText("");
        TextoCabeza.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        TextoCabeza.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        Nombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Nombre.setText("Nombre(s):");

        Apellido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Apellido.setText("Apellido(s):");

        CI.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CI.setText("Carnet de identidad:");

        Telf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Telf.setText("Telefono:");

        Direccion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Direccion.setText("Direccion:");

        Correo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Correo.setText("Correo:");

        EquipoLavado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EquipoLavado.setText("Equipo de lavados:");

        CITxt.setForeground(new java.awt.Color(204, 204, 204));
        CITxt.setText("Ingrese CI");
        CITxt.setCaretColor(new java.awt.Color(204, 204, 204));
        CITxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CITxtActionPerformed(evt);
            }
        });

        TelfTxt.setForeground(new java.awt.Color(204, 204, 204));
        TelfTxt.setText("Ingrese telefono");

        DireccionTxt.setForeground(new java.awt.Color(204, 204, 204));
        DireccionTxt.setText("Ingrese direccion");

        CorreoTxt.setForeground(new java.awt.Color(204, 204, 204));
        CorreoTxt.setText("Ingrese correo");
        CorreoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoTxtActionPerformed(evt);
            }
        });

        EquipoLavadoTxt.setForeground(new java.awt.Color(204, 204, 204));
        EquipoLavadoTxt.setText("Seleccione equipo");

        NombreTxt.setForeground(new java.awt.Color(204, 204, 204));
        NombreTxt.setText("Ingrese su nombre");
        NombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTxtActionPerformed(evt);
            }
        });

        ApellidoTxt.setForeground(new java.awt.Color(204, 204, 204));
        ApellidoTxt.setText("Ingrese su apellido");
        ApellidoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoTxtActionPerformed(evt);
            }
        });

        Foto.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout FotoLayout = new javax.swing.GroupLayout(Foto);
        Foto.setLayout(FotoLayout);
        FotoLayout.setHorizontalGroup(
            FotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );
        FotoLayout.setVerticalGroup(
            FotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        FotoBT.setText("Insertar Foto");
        FotoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FotoBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCentralLayout = new javax.swing.GroupLayout(PanelCentral);
        PanelCentral.setLayout(PanelCentralLayout);
        PanelCentralLayout.setHorizontalGroup(
            PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCentralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TextoCabeza, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCentralLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCentralLayout.createSequentialGroup()
                        .addComponent(EquipoLavado)
                        .addGap(18, 18, 18)
                        .addComponent(EquipoLavadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCentralLayout.createSequentialGroup()
                        .addComponent(Correo)
                        .addGap(18, 18, 18)
                        .addComponent(CorreoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCentralLayout.createSequentialGroup()
                        .addComponent(Direccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DireccionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCentralLayout.createSequentialGroup()
                        .addComponent(Telf)
                        .addGap(18, 18, 18)
                        .addComponent(TelfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCentralLayout.createSequentialGroup()
                        .addComponent(CI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CITxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCentralLayout.createSequentialGroup()
                        .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Apellido)
                            .addComponent(Nombre))
                        .addGap(18, 18, 18)
                        .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ApellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCentralLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(Foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(212, 212, 212))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCentralLayout.createSequentialGroup()
                        .addComponent(FotoBT)
                        .addGap(238, 238, 238))))
        );
        PanelCentralLayout.setVerticalGroup(
            PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCentralLayout.createSequentialGroup()
                .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCentralLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelCentralLayout.createSequentialGroup()
                                .addComponent(TextoCabeza, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Nombre)
                                    .addComponent(NombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Apellido)
                                    .addComponent(ApellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CI)
                                    .addComponent(CITxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Telf)
                            .addComponent(TelfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelCentralLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(FotoBT)))
                .addGap(18, 18, 18)
                .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Direccion)
                    .addComponent(DireccionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Correo)
                    .addComponent(CorreoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EquipoLavado)
                    .addComponent(EquipoLavadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(433, Short.MAX_VALUE))
        );

        Background.add(PanelCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 110, 984, 860));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Background.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InicioBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InicioBTActionPerformed

    private void CotizacionBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CotizacionBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CotizacionBTActionPerformed

    private void LogoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoBTActionPerformed

    private void SoporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoporteActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void ApellidoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoTxtActionPerformed
       
    }//GEN-LAST:event_ApellidoTxtActionPerformed

    private void CITxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CITxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CITxtActionPerformed

    private void CorreoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoTxtActionPerformed

    private void NombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtActionPerformed

    private void FotoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FotoBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FotoBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registroEmpleadoInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registroEmpleadoInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registroEmpleadoInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registroEmpleadoInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registroEmpleadoInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JTextField ApellidoTxt;
    private javax.swing.JPanel Background;
    private com.mycompany.proyectolavadero.Interfaces.PanelRound Busqueda;
    private javax.swing.JLabel CI;
    private javax.swing.JTextField CITxt;
    private javax.swing.JButton CatalogoBT;
    private javax.swing.JButton ClientesBT;
    private javax.swing.JLabel Correo;
    private javax.swing.JTextField CorreoTxt;
    private javax.swing.JButton CotizacionBT;
    private javax.swing.JLabel Direccion;
    private javax.swing.JTextField DireccionTxt;
    private javax.swing.JButton EquipoBT;
    private javax.swing.JLabel EquipoLavado;
    private javax.swing.JTextField EquipoLavadoTxt;
    private javax.swing.JPanel Foto;
    private javax.swing.JButton FotoBT;
    private javax.swing.JButton InicioBT;
    private javax.swing.JButton InventarioBT;
    private javax.swing.JButton LogoBT;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JPanel PanelCentral;
    private javax.swing.JPanel PanelIzq;
    private javax.swing.JPanel PanelSuperior;
    private javax.swing.JButton ReportesBT;
    private javax.swing.JButton Soporte;
    private javax.swing.JLabel Telf;
    private javax.swing.JTextField TelfTxt;
    private javax.swing.JLabel TextoCabeza;
    private javax.swing.JButton Usuario;
    private javax.swing.JButton VehiculosBT;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
